from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.saucedemo.com/")
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("standard_user")
    page.locator("[data-test=\"username\"]").press("Tab")
    page.locator("[data-test=\"password\"]").fill("secret_sauce")
    page.locator("[data-test=\"login-button\"]").click()
    expect(page.locator("[data-test=\"item-4-title-link\"]")).to_be_visible()
    page.locator("[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    page.locator("[data-test=\"shopping-cart-link\"]").click()
    expect(page.get_by_text("1Sauce Labs Backpackcarry.")).to_be_visible()
    expect(page.get_by_text("1Sauce Labs Bike LightA red")).to_be_visible()
    page.locator("[data-test=\"checkout\"]").click()
    page.locator("[data-test=\"firstName\"]").click()
    page.locator("[data-test=\"firstName\"]").fill("test")
    page.locator("[data-test=\"firstName\"]").press("Tab")
    page.locator("[data-test=\"lastName\"]").fill("test")
    page.locator("[data-test=\"lastName\"]").press("Tab")
    page.locator("[data-test=\"postalCode\"]").fill("123")
    page.locator("[data-test=\"continue\"]").click()
    expect(page.get_by_text("1Sauce Labs Backpackcarry.")).to_be_visible()
    expect(page.get_by_text("1Sauce Labs Bike LightA red")).to_be_visible()
    expect(page.locator("[data-test=\"subtotal-label\"]")).to_contain_text("Item total: $39.98")
    page.locator("[data-test=\"finish\"]").click()
    expect(page.locator("[data-test=\"complete-header\"]")).to_contain_text("Thank you for your order!")
    expect(page.locator("[data-test=\"complete-text\"]")).to_contain_text("Your order has been dispatched, and will arrive just as fast as the pony can get there!")
    page.locator("[data-test=\"back-to-products\"]").click()
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
